alerting:
  alerts_paused:
    double_check: false
    double_forecast: false
    forecast: false
    regression: false
  forecast_percentage: 0.05
  paused: false
  paused_time: 0
  regression_min_difference: 10
  regression_percentage: 0.05
arima:
  forecast_time: 60
  forecast_training_time: 300
  metrics:
  - incoming_task_count_total-BASIC_PREPARATION:
    - constant_yes:
        d: 1
        p: 5
        q: 4
        trend: c
    - constant_no:
        d: 1
        p: 5
        q: 4
        trend: nc
  - incoming_task_count_total-CREATE_JPEGS:
    - constant_yes:
        d: 1
        p: 6
        q: 7
        trend: c
    - constant_no:
        d: 1
        p: 6
        q: 7
        trend: nc
  - incoming_task_count_total-FUBO:
    - constant_yes:
        d: 1
        p: 1
        q: 0
        trend: c
    - constant_no:
        d: 1
        p: 0
        q: 1
        trend: nc
  - incoming_task_count_total-PMT:
    - constant_yes:
        d: 1
        p: 6
        q: 4
        trend: c
    - constant_no:
        d: 1
        p: 6
        q: 4
        trend: nc
  - incoming_task_count_total-TOA:
    - constant_yes:
        d: 1
        p: 3
        q: 3
        trend: c
    - constant_no:
        d: 1
        p: 3
        q: 3
        trend: nc
  - incoming_task_count_total-TOA_4K:
    - constant_yes:
        d: 1
        p: 1
        q: 0
        trend: c
    - constant_no:
        d: 1
        p: 0
        q: 1
        trend: nc
  - incoming_task_count_total-VESET_BELGIUM:
    - constant_yes:
        d: 1
        p: 2
        q: 3
        trend: c
    - constant_no:
        d: 1
        p: 2
        q: 3
        trend: nc
  - task_in_failure:
    - constant_yes:
        d: 0
        p: 1
        q: 0
        trend: c
monitoring:
  app: '''task-manager'''
  datacenter: '''atlas-xcms-eu-west1'''
  kubernetes_namespace: '''production-task-manager'''
  time_span: 60
  time_span_sleep: 5
regression:
- incoming_task_count_total-BASIC_PREPARATION:
    constant: '+0.1698370365'
    manual_error: 78.0
    metrics:
    - incoming_event_count_total:
        event_type: FINISHED
        exp: '1'
        value: '+0.6418051577'
    - incoming_event_count_total:
        event_type: STARTED
        exp: '1'
        value: '+0.3548617659'
    - incoming_event_count_total:
        event_type: TERMINATED
        exp: '1'
        value: '-1.0804571699'
    - incoming_event_count_total:
        event_type: ERROR
        exp: '1'
        value: '-1.2507085187'
    predict: incoming_task_count_total
    task_type: BASIC_PREPARATION
- incoming_task_count_total-CREATE_JPEGS:
    constant: '-0.0237419063'
    manual_error: 0
    metrics:
    - incoming_event_count_total:
        event_type: FINISHED
        exp: '1'
        value: '+1.1753293496'
    - incoming_event_count_total:
        event_type: STARTED
        exp: '1'
        value: '-0.1714397297'
    - incoming_event_count_total:
        event_type: TERMINATED
        exp: '1'
        value: '-2.9493092472'
    - incoming_event_count_total:
        event_type: ERROR
        exp: '1'
        value: '0.3570134778'
    predict: incoming_task_count_total
    task_type: CREATE_JPEGS
- incoming_task_count_total-FUBO:
    constant: '-7.8718054068'
    manual_error: 0
    metrics:
    - incoming_event_count_total:
        event_type: FINISHED
        exp: '1'
        value: '-1.6098391394'
    - incoming_event_count_total:
        event_type: STARTED
        exp: '1'
        value: '+2.7462404654'
    - incoming_event_count_total:
        event_type: TERMINATED
        exp: '1'
        value: '-2.9493092472'
    - incoming_event_count_total:
        event_type: ERROR
        exp: '1'
        value: '-1.3570134778'
    predict: incoming_task_count_total
    task_type: FUBO
- incoming_task_count_total-PMT:
    constant: '+2.2319223380'
    manual_error: 0
    metrics:
    - incoming_event_count_total:
        event_type: FINISHED
        exp: '1'
        value: '-1.0587647440'
    - incoming_event_count_total:
        event_type: STARTED
        exp: '1'
        value: '+1.6666665789'
    - incoming_event_count_total:
        event_type: TERMINATED
        exp: '1'
        value: '+0.7555271460'
    predict: incoming_task_count_total
    task_type: PMT
- incoming_task_count_total-TOA:
    constant: '+2.4275736945'
    manual_error: -12.0
    metrics:
    - incoming_event_count_total:
        event_type: FINISHED
        exp: '1'
        value: '-1.1716673056'
    - incoming_event_count_total:
        event_type: STARTED
        exp: '1'
        value: '+1.9749673030'
    - incoming_event_count_total:
        event_type: TERMINATED
        exp: '1'
        value: '+3.7246558313'
    - incoming_event_count_total:
        event_type: ERROR
        exp: '1'
        value: '+1.3570134778'
    predict: incoming_task_count_total
    task_type: TOA
- incoming_task_count_total-TOA_4K:
    constant: '+0.0574014464'
    manual_error: 0.0
    metrics:
    - incoming_event_count_total:
        event_type: FINISHED
        exp: '1'
        value: '+0.8299544263'
    - incoming_event_count_total:
        event_type: STARTED
        exp: '1'
        value: '+0.0544166535'
    - incoming_event_count_total:
        event_type: TERMINATED
        exp: '1'
        value: '-0.6298745827'
    - incoming_event_count_total:
        event_type: ERROR
        exp: '1'
        value: '+0.4048063982'
    predict: incoming_task_count_total
    task_type: TOA_4K
- incoming_task_count_total-VESET_BELGIUM:
    constant: '-2.0462340711'
    manual_error: 3.0
    metrics:
    - incoming_event_count_total:
        event_type: FINISHED
        exp: '1'
        value: '+0.2795809316'
    - incoming_event_count_total:
        event_type: STARTED
        exp: '1'
        value: '+0.7514808520'
    - incoming_event_count_total:
        event_type: TERMINATED
        exp: '1'
        value: '-4.7513967377'
    - incoming_event_count_total:
        event_type: ERROR
        exp: '1'
        value: '-0.7936176176'
    predict: incoming_task_count_total
    task_type: VESET_BELGIUM
- task_in_failure:
    constant: '82.4726007449'
    manual_error: -18.0
    metrics:
    - incoming_event_count_total:
        event_type: ERROR
        exp: '1'
        value: '+3.0159812487'
    predict: task_in_failure
    task_type: BASIC_PREPARATION
server:
  url: http://prometheus.xite.com:9090
slack:
  channel: CCKHS9DBJ
  token: xoxb-428326618882-651131019078-j3m1goldPEUVJvlTVu0sQ6re
