alerting:
  forecast_percentage: 0.05
  paused: false
  regression_percentage: 0.15
arima:
  forecast_time: 60
  forecast_training_time: 300
  metrics:
  - incoming_task_count_total-BASIC_PREPARATION:
    - constant_yes:
        d: 1
        p: 4
        q: 0
        trend: c
    - constant_no:
        d: 1
        p: 0
        q: 13
        trend: nc
  - incoming_task_count_total-CREATE_JPEGS:
    - constant_yes:
        d: 1
        p: 6
        q: 0
        trend: c
    - constant_no:
        d: 1
        p: 0
        q: 8
        trend: nc
  - incoming_task_count_total-FUBO:
    - constant_yes:
        d: 1
        p: 1
        q: 0
        trend: c
    - constant_no:
        d: 1
        p: 0
        q: 1
        trend: nc
  - incoming_task_count_total-PMT:
    - constant_yes:
        d: 1
        p: 6
        q: 0
        trend: c
    - constant_no:
        d: 1
        p: 0
        q: 13
        trend: nc
  - incoming_task_count_total-TOA:
    - constant_yes:
        d: 1
        p: 4
        q: 0
        trend: c
    - constant_no:
        d: 1
        p: 0
        q: 10
        trend: nc
  - incoming_task_count_total-TOA_4K:
    - constant_yes:
        d: 1
        p: 1
        q: 0
        trend: c
    - constant_no:
        d: 1
        p: 0
        q: 1
        trend: nc
  - incoming_task_count_total-VESET_BELGIUM:
    - constant_yes:
        d: 1
        p: 2
        q: 0
        trend: c
    - constant_no:
        d: 1
        p: 0
        q: 3
        trend: nc
  - task_in_failure:
    - constant_yes:
        d: 0
        p: 13
        q: 0
        trend: c
monitoring:
  app: '''task-manager'''
  datacenter: '''atlas-xcms-eu-west1'''
  kubernetes_namespace: '''production-task-manager'''
  time_span: 60
  time_span_sleep: 5
regression:
- incoming_task_count_total-BASIC_PREPARATION:
    constant: '+4.9257723939'
    metrics:
    - incoming_event_count_total:
        event_type: FINISHED
        exp: '1'
        value: '-1.9427715755'
    - incoming_event_count_total:
        event_type: STARTED
        exp: '1'
        value: '+2.8701723231'
    - incoming_event_count_total:
        event_type: TERMINATED
        exp: '1'
        value: '-0.1042482924'
    predict: incoming_task_count_total
    task_type: BASIC_PREPARATION
- incoming_task_count_total-CREATE_JPEGS:
    constant: '+1.3642873561'
    metrics:
    - incoming_event_count_total:
        event_type: FINISHED
        exp: '1'
        value: '-1.1012672705'
    - incoming_event_count_total:
        event_type: STARTED
        exp: '1'
        value: '+2.0970134380'
    - incoming_event_count_total:
        event_type: TERMINATED
        exp: '2'
        value: '-0.5041718980'
    predict: incoming_task_count_total
    task_type: CREATE_JPEGS
- incoming_task_count_total-FUBO:
    constant: '-7.8718054068'
    metrics:
    - incoming_event_count_total:
        event_type: FINISHED
        exp: '1'
        value: '-1.6098391394'
    - incoming_event_count_total:
        event_type: STARTED
        exp: '1'
        value: '+2.7462404654'
    predict: incoming_task_count_total
    task_type: FUBO
- incoming_task_count_total-PMT:
    constant: '+2.2319223380'
    metrics:
    - incoming_event_count_total:
        event_type: FINISHED
        exp: '1'
        value: '-1.0587647440'
    - incoming_event_count_total:
        event_type: STARTED
        exp: '1'
        value: '+1.6666665789'
    - incoming_event_count_total:
        event_type: TERMINATED
        exp: '1'
        value: '+0.7555271460'
    predict: incoming_task_count_total
    task_type: PMT
- incoming_task_count_total-TOA:
    constant: '+2.4275736945'
    metrics:
    - incoming_event_count_total:
        event_type: FINISHED
        exp: '1'
        value: '-1.1716673056'
    - incoming_event_count_total:
        event_type: STARTED
        exp: '1'
        value: '+1.9749673030'
    - incoming_event_count_total:
        event_type: TERMINATED
        exp: '1'
        value: '+3.7246558313 '
    predict: incoming_task_count_total
    task_type: TOA
- incoming_task_count_total-TOA_4K:
    constant: '-1.9996214927'
    metrics:
    - incoming_event_count_total:
        event_type: FINISHED
        exp: '1'
        value: '+0.5782614032'
    - incoming_event_count_total:
        event_type: STARTED
        exp: '1'
        value: '+0.3926033457'
    - incoming_event_count_total:
        event_type: TERMINATED
        exp: '1'
        value: '-1.3018056615'
    predict: incoming_task_count_total
    task_type: TOA_4K
- incoming_task_count_total-VESET_BELGIUM:
    constant: '-3.6225320092'
    metrics:
    - incoming_event_count_total:
        event_type: FINISHED
        exp: '1'
        value: '0.3502647401'
    - incoming_event_count_total:
        event_type: STARTED
        exp: '1'
        value: '+0.6948983163'
    - incoming_event_count_total:
        event_type: TERMINATED
        exp: '1'
        value: '-4.9593665539'
    predict: incoming_task_count_total
    task_type: VESET_BELGIUM
- task_in_failure:
    constant: '52.0885583682'
    metrics:
    - incoming_event_count_total:
        event_type: ERROR
        exp: '1'
        value: '+0.3588034606'
    predict: task_in_failure
    task_type: BASIC_PREPARATION
server:
  url: http://prometheus.xite.com:9090
slack:
  channel: CCKHS9DBJ
  token: xoxb-428326618882-651131019078-j3m1goldPEUVJvlTVu0sQ6re
